# site
# --- editar y ajustar de acuerdo al curso 
site_name: Introducción a la Bioinformática
site_description: "Sitio Web del Curso Introducción a la Bioinformática"
#site_author: "Nombre Apellido"
site_url: https://bioinformatica-iib.github.io/introduccion_bioinformatica/

# repository
# --- si el sitio está alojado en un repo, describirlo acá 
# repo_name: 'introduccion_bioinformatica'
# repo_url: https://github.com/bioinformatica-iib/introduccion_bioinformatica

# theme 
# --- customizar apariencia editando palette 
# --- consultar https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
theme:
  logo: 'img/logo-unsam-negro.png'  # este logo es el que aparece al lado del nombre del curso
  favicon: img/logo-unsam-negro.png # este logo es el que aparece en la pestaña del chrome
  name: material
  font: 
    text: Cabin
    code: Roboto Mono
  language: es 
  features:
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.tracking
    - navigation.tabs
#    - navigation.sections
#    - navigation.tabs.sticky # --> hace que la navigation bar baje cuando se escrolea.
#    - navigation.indexes # Si se saca, cada section del index se puede ampliar INCOMPATIBLE CON toc.integrate y creo que con navigation tracking
    - toc.integrate # Integra la table of contents a la navigation
    - navigation.top
    
  palette: 
    - scheme: default
      primary: custom 
      accent: deep orange
      toggle:
        icon: material/toggle-switch 
        name: Cambiar a modo oscuro
    - scheme: slate 
      primary: custom
      accent: deep orange
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Cambiar a modo claro

# plugins
plugins:
  - search
  - mkdocs-video 
  - awesome-pages
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: "100%"
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom

  #- git-revision-date
  #- tags:
      #tags_file: tags.md # En particular no me parecieron útiles

# markdown extensions
markdown_extensions:
  - abbr
  - meta
  - admonition
  - footnotes
  - attr_list
  - def_list
  - md_in_html
  - toc:
      title: Contenidos
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all

# extra
# --- editar los URLs, agregar los links especificos a cada cuenta, canal, etc. 
# --- reordenar los bloques de iconos + links de acuerdo al gusto
#extra:
#  social:
#    - icon: fontawesome/brands/slack
#      link: https://workspace-name.slack.com
#   - icon: fontawesome/brands/github
#     link: https://github.com/repo/name
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/cuenta
#    - icon: fontawesome/brands/youtube
#      link: https://youtube.com/channel/channel-id
#    - icon: fontawesome/brands/discord
#      link: https://discord.com/server

# extra++
extra_javascript:
  # Este es el paquete tablesort que permite que las tablas
  # se puedan ordenar según la columna:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js 
  # y este es el codigo javascript para usar tablesort:
  - javascripts/tablesort.js
  # Estos son los paquetes JavaScript para usar MathJax - formulas matemáticas
  # ver: https://docs.mathjax.org/en/latest/web/start.html
  - https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # y este es Javascript minimo para procesar MathJax con arithmatex
  - javascripts/mathjax.js 

extra_css:
  - stylesheets/extra.css

# Esto organiza lo que es la navegación. El nivel más alto (Inicio, Acerca de, etc) va a ser una pestaña en la barra de navegación
# No hay dropdowns pero aparece en una navigation bar al costado que se puede o no integrar con la tabla de contenidos (comentando o descomentando toc.integrate en theme --> features -toc.integrate). 
nav:
    - Inicio: 'index.md'
    - Acerca de: 'acerca.md'
    - Cómo Llegar: 'comollegar.md'
    - Contenidos: 'contenidos.md'
    - Cronograma: 'cronograma.md'
    - Docentes: 'docentes.md'
    - Teóricas:
        - teoricas/inicio.md
        - Teórica 1: teoricas/1-Teorica-Uno/index.md
        - Teórica 2: teoricas/2-Teorica-Dos/index.md
        # - Teórica 3: teoricas/3-Teorica-Tres/index.md
        # - Teórica 4: teoricas/4-Teorica-Cuatro/index.md
        # - Teórica 5: teoricas/5-Teorica-Cinco/index.md
        # - Teórica 6: teoricas/6-Teorica-Seis/index.md 
        # - Teórica 7: teoricas/7-Teorica-Siete/index.md
        # - Teórica 8: teoricas/8-Teorica-Ocho/index.md
        # - Teórica 9: teoricas/9-Teorica-Nueve/index.md
        # - Teórica 10: teoricas/10-Teorica-Diez/index.md
        # - Teórica 11: teoricas/11-Teorica-Once/index.md
        # - Teórica 12: teoricas/12-Teorica-Doce/index.md
        #- Resumen: teoricas/resumen.md

    - Prácticos: 
        - 'practicos/inicio.md'
        #- TPs: 'practicos/tpsGrid.md'
        - TP 1 - Linux: 'practicos/TP01_Linux/index.md'
        - TP 2 - EMBOSS: 'practicos/TP02_EMBOSS/index.md'
        # - TP 3 - Alineamientos de a pares: 'practicos/TP03_Alineamientos/index.md'
        #- TP 4 - Búsqueda por similitud: 'practicos/TP04_Busqueda_por_similitud/index.md'
        #- TP 5a - R - Introduccion: 'practicos/TP05a_R/index.md'
        #- TP 5b - R - Aplicación: 'practicos/TP05b_R/index.md' 
        #- TP 6 - PSI-BLAST: 'practicos/TP06_PSI-BLAST/index.md'
        #- TP 7 - Predicción de Desorden: 'practicos/TP07_Desorden/index.md'
        #- TP 8 - Motivos Lineales: 'practicos/TP08_Motivos/index.md'
        #- TP 9a - Modelado por Homología: 'practicos/TP09a_Modelado_Por_Homologia/index.md'
        #- TP 9b - Modelado usando AlphaFold: 'practicos/TP09b_AlphaFold/index.md'
        #- TP 10a - Clustering: 'practicos/TP10a_Clustering/index.md'
        #- TP 10b - Data Mining: 'practicos/TP10b_Data_Mining/index.md'
        #- TP 11 - HMMs & ANNs: 'practicos/TP11_HMM_ANN/index.md'
        #- TP 12 - Short Read Mapping: 'practicos/TP12_Short-Read-Mapping/index.md'
        #- TP 13 - Genomica Comparativa: 'practicos/TP13_Genomica_Comparativa/index.md'
        #- TP 14 - Quimioinformatica: 'practicos/TP14_Quimioinformatica/index.md'
      #  - TP 6 - Filogenias: 'practicos/TP06_Filogenia/index.md'

        #- Resumen: 'practicos/resumen.md'

    - Instructivos:
        - 'instructivos/inicio.md'
        - Replit: 'instructivos/replit/index.md' 
    #     - Máquina Virtual: 'instructivos/maquina_virtual/index.md'
    #     - Problemas instalando la Máquina Virtual: 'instructivos/problemasVM/index.md'
    #     - Tips and Tricks para usar la Máquina Virtual más cómodos: 'instructivos/tipsVM/index.md'

# copyright
# --- editar y ajustar de acuerdo al curso
copyright: Copyright &copy; 2024 Area Bioinformática UNSAM  
