# site
# --- editar y ajustar de acuerdo al curso 
site_name: Introducción a la Bioinformática
site_description: "Sitio Web del Curso Introducción a la Bioinformática"
#site_author: "Nombre Apellido"
site_url: https://bioinformatica-iib.github.io/2022_introduccion_bioinformatica/

# repository
# --- si el sitio está alojado en un repo, describirlo acá 
# repo_name: '2022_introduccion_bioinformatica'
# repo_url: https://github.com/bioinformatica-iib/2022_introduccion_bioinformatica

# theme 
# --- customizar apariencia editando palette 
# --- consultar https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
theme:
  logo: 'img/favicon.png'  # este logo es el que aparece al lado del nombre del curso
  favicon: img/favicon.png # este logo es el que aparece en la pestaña del chrome
  name: material
  language: es 
  features:
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.tracking
    - navigation.tabs
#    - navigation.sections
#    - navigation.tabs.sticky # --> hace que la navigation bar baje cuando se escrolea.
#    - navigation.indexes # Si se saca, cada section del index se puede ampliar INCOMPATIBLE CON toc.integrate y creo que con navigation tracking
    - toc.integrate # Integra la table of contents a la navigation
    - navigation.top
    
  palette: 
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch 
        name: Cambiar a modo oscuro
    - scheme: slate 
      primary: indigo
      accent: indigo
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Cambiar a modo claro

# plugins
plugins:
  - search
  - mkdocs-video 
  - awesome-pages

  #- git-revision-date
  #- tags:
      #tags_file: tags.md # En particular no me parecieron útiles

# markdown extensions
markdown_extensions:
  - meta
  - admonition
  - footnotes
  - attr_list
  - def_list
  - md_in_html
  - toc:
      title: Contenidos
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

# extra
# --- editar los URLs, agregar los links especificos a cada cuenta, canal, etc. 
# --- reordenar los bloques de iconos + links de acuerdo al gusto
#extra:
#  social:
#    - icon: fontawesome/brands/slack
#      link: https://workspace-name.slack.com
#   - icon: fontawesome/brands/github
#     link: https://github.com/repo/name
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/cuenta
#    - icon: fontawesome/brands/youtube
#      link: https://youtube.com/channel/channel-id
#    - icon: fontawesome/brands/discord
#      link: https://discord.com/server

# extra++
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js # Esto permite que las tablas se puedan ordenar según la columna. Lo que no vi es como hacerlo selectivo para cada tabla.
  - javascripts/tablesort.js
  - javascripts/mathjax.js # Esto es para formulas matematicas
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

# Esto organiza lo que es la navegación. El nivel más alto (Inicio, Acerca de, etc) va a ser una pestaña en la barra de navegación
# No hay dropdowns pero aparece en una navigation bar al costado que se puede o no integrar con la tabla de contenidos (comentando o descomentando toc.integrate en theme --> features -toc.integrate). 
nav:
    - Inicio: 'index.md'
    - Acerca de: 'acerca.md'
    - Contenidos: 'contenidos.md'
    - Cronograma: 'cronograma.md'
    - Docentes: 'docentes.md'
    - Teoricas:
        - teoricas/inicio.md
        - Teórica 1: teoricas/1-Teorica-Uno/index.md
        - Teórica 2: teoricas/2-Teorica-Dos/index.md
        - Teórica 3: teoricas/3-Teorica-Tres/index.md
        - Teórica 4: teoricas/4-Teorica-Cuatro/index.md
        - Teórica 5: teoricas/5-Teorica-Cinco/index.md
        - Teórica 6: teoricas/6-Teorica-Seis/index.md
        - Teórica 7: teoricas/7-Teorica-Siete/index.md
        - Teórica 8: teoricas/8-Teorica-Ocho/index.md
        - Teórica 9: teoricas/9-Teorica-Nueve/index.md
        - Teórica 10: teoricas/10-Teorica-Diez/index.md
        - Teórica 11: teoricas/11-Teorica-Once/index.md
        - Teórica 12: teoricas/12-Teorica-Doce/index.md
        #- Resumen: teoricas/resumen.md

    - Prácticos: 
        - 'practicos/inicio.md'
        #- TPs: 'practicos/tpsGrid.md'
        - TP 1 - Linux: 'practicos/TP01_Linux/index.md'
        - TP 2 - EMBOSS: 'practicos/TP02_EMBOSS/index.md'
        - TP 3 - Alineamientos de a pares: 'practicos/TP03_Alineamientos/index.md'
        - TP 4 - Búsqueda por similitud: 'practicos/TP04_Busqueda_por_similitud/index.md'
        - TP 5 - Perfiles de secuencias: 'practicos/TP05_PSI-BLAST/index.md'
        - TP 6 - Filogenias: 'practicos/TP06_Filogenia/index.md'
        - TP 7 - HMMs & ANNs: 'practicos/TP07_HMM_ANN/index.md'
        - TP 8a - R - Introducción: 'practicos/TP08a_R/index.md'
        - TP 8b - R - Aplicación: 'practicos/TP08b_R/index.md'
        - TP 9 - Predicción de Desorden: 'practicos/TP09_Desorden/index.md'
        - TP 10 - Motivos Lineales: 'practicos/TP10_Motivos/index.md'
        - TP 11 - Modelado por Homología: 'practicos/TP11_Modelado_Por_Homologia/index.md'
        - TP 12a - Clustering: 'practicos/TP12a_Clustering/index.md'
        - TP 12b - Data Mining: 'practicos/TP12b_Data_Mining/index.md'
        - TP 13 - Short Read Mapping: 'practicos/TP13_Short-Read-Mapping/index.md'
        - TP 14 - Genomica Comparativa: 'practicos/TP14_Genomica_Comparativa/index.md'

        #- Resumen: 'practicos/resumen.md'

    - Instructivos:
        - instructivos/inicio.md
        - Máquina Virtual: 'instructivos/maquina_virtual/index.md'
        - Problemas instalando la Máquina Virtual: 'instructivos/problemasVM/index.md'
        - Tips and Tricks para usar la Máquina Virtual más cómodos: 'instructivos/tipsVM/index.md'

# copyright
# --- editar y ajustar de acuerdo al curso
copyright: Copyright &copy; 2022 Area Bioinformatica UNSAM  
